### ISSUE TITLE
Changing Versions

### ISSUE THREAD

**Issue by xploz1on** [damalis/full-stack-proxy-nginx-prestashop-for-everyone-with-docker-compose#1]
Hey there. First of all this is super awesome!!! Amazing job!

So I have been digging into the files and here are some questions:

To change Prestashop version. I would have to edit the url in the docker-compose file
```
wget -P /tmp/data-pres https://github.com/PrestaShop/PrestaShop/releases/download/8.0.1/prestashop_8.0.1.zip && unzip -q /tmp/data-pres/prestashop_8.0.1.zip -d 
```
And change it to the version I want to install. Same goes for php and SQL in .env file.

Could I simply do a 'docker compose down' make changes and 'docker compose up -d' So I keep the SSL certs and everything, just change the version of say php, mysql?

Just kinda looking for a quick way to change versions. I am currently going to update a prestashop 1.7.6.0

Again, amazing job @damalis  !

**Comment by damalis** [comment]
The best solotion: [here](https://www.a2hosting.com/kb/installable-applications/optimization-and-configuration/prestashop2/updating-prestashop/#Method-2.3A-Manual-update)

**Comment by xploz1on** [comment]
> The best solotion: [here](https://www.a2hosting.com/kb/installable-applications/optimization-and-configuration/prestashop2/updating-prestashop/#Method-2.3A-Manual-update)

Thank you. After so much testing, updating using the shop solution is the best.
